# Customized for ArloBot
max_obstacle_height: 0.60  # assume something like an arm is mounted on top of the robot
obstacle_range: 2.5 # 2.5 meters the robot can see only obstacles thats is about 2.5 meters and less 
raytrace_range: 3.0 # 3 meters

# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
footprint: [[0.3, 0.23], [0.3, -0.23], [-0.3, 0.23],[-0.3,-0.23]]  # if the robot is not circular
inflation_radius: 0.50  # max. distance from an obstacle at which costs are incurred for planning paths.
cost_scaling_factor: 5  # exponential rate at which the obstacle cost drops off (default: 10)

map_type: costmap
transform_tolerance: 5 # seconds


origin_z: 0.0
z_resolution: 0.2
z_voxels: 2
publish_voxel_map: false

observation_sources: scan

scan: {data_type: LaserScan, topic: scan, marking: true, clearing: true, min_obstacle_height: 0.0, max_obstacle_height: 3}
